routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Auth\SessionController@login')->name('login');
Route::post('/login', 'Auth\SessionController@postLogin')->name('login');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'DashboardController@index');
    Route::get('logout', 'Auth\SessionController@logout');

    Route::get('change_password', 'Auth\PasswordManagerController@changePassword');
    Route::post('change_password', 'Auth\PasswordManagerController@postChangePassword');

    Route::get('lectures', 'LectureController@index');
    Route::get('lectures/download_class_note/{lecture_id}', 'LectureController@downloadClassNote');
    Route::get('lectures/download_lecture_sheet/{lecture_id}', 'LectureController@downloadLectureSheet');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::namespace('Admin')->group(function () {
        Route::prefix('admin')->group(function () {
            Route::resource('lectures', 'LectureController')->except(['show']);
            Route::resource('users', 'UserController')->except(['show']);
            Route::resource('batches', 'BatchController')->except(['show']);
            Route::resource('subjects', 'SubjectController')->except(['show']);
            Route::resource('configs', 'ConfigController')->except(['show']);

            Route::get('passwords/reset/{user_id}', 'PasswordManagerController@resetPassword');
            Route::post('passwords/reset/{user_id}', 'PasswordManagerController@postResetPassword');
        });
    });
});

app/Http/Controllers/Admin/SubjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Subject\CreateSubjectValidation;
use App\Http\Requests\Admin\Subject\EditSubjectValidation;
use App\Model\Subject;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjects = Subject::withCount('lectures')->get();

        return view('admin.subjects.index', compact('subjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.subjects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateSubjectValidation $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSubjectValidation $request)
    {
        Subject::create(['name' => $request->get('name')]);

        return redirect('admin/subjects')->with('successMessage', 'Subject created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subject = Subject::find($id);

        return view('admin.subjects.edit', compact('subject'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  EditSubjectValidation $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditSubjectValidation $request, $id)
    {
        $subject = Subject::find($id);
        if ($subject) {
            $subject->update(['name' => $request->get('name')]);
        }

        return redirect('admin/subjects')->with('successMessage', 'Subject updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subject = Subject::find($id);
        if ($subject) {
            $subject->delete();
        }

        return redirect('admin/subjects')->with('successMessage', 'Subject deleted successfully');
    }
}

resources/views/admin/subjects/create.blade.php
@extends('layout.layout')
@section('title', 'Subject create')
@section('header')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active">Subject create</li>
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Subject create</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{url('admin/subjects')}}" class="btn btn-primary float-right">
                        <i class="fas fa-arrow-left"></i> Back to list</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-body">
                        <form action="{{url('admin/subjects')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name <span class="color-red">*</span></label>
                                <input type="text" id="name" name="name" value="{{old('name')}}"
                                       class="form-control <?php if ($errors->first('name') != null) echo 'is-invalid'; ?>">
                                <span class="error <?php if ($errors->first('name') != null) echo 'invalid-feedback'; ?>"
                                      style="display: inline;">{{$errors->first('name')}}</span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-success float-right">
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('footer')
@endsection

resources/views/admin/subjects/edit.blade.php
@extends('layout.layout')
@section('title', 'Subject edit')
@section('header')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active">Subject edit</li>
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Subject edit</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{url('admin/subjects')}}" class="btn btn-primary float-right">
                        <i class="fas fa-arrow-left"></i> Back to list</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-body">
                        <form action="{{url('admin/subjects/'.$subject->id)}}" method="post">
                            @csrf
                            @method('put')
                            <div class="form-group">
                                <label for="name">Name <span class="color-red">*</span></label>
                                <input type="text" id="name" name="name"
                                       class="form-control <?php if ($errors->first('name') != null) echo 'is-invalid'; ?>"
                                       value="{{old('name',$subject->name)}}">
                                <span class="error <?php if ($errors->first('name') != null) echo 'invalid-feedback'; ?>"
                                      style="display: inline;">{{$errors->first('name')}}</span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Update" class="btn btn-success float-right">
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('footer')
@endsection

resources/views/admin/subjects/index.blade.php
@extends('layout.layout')
@section('title', 'Subject list')
@section('header')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('resources/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet"
          href="{{asset('resources/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active">Subject list</li>
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Subject list</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{url('admin/subjects/create')}}" class="btn btn-primary float-right">
                        <i class="fas fa-plus"></i> Create new</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-body">
                @include('layout.flash_message')
                <table id="example" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th width="50%">Name</th>
                        <th>Number of lectures</th>
                        <th width="10%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($subjects as $subject)
                        <tr>
                            <td>{{$subject->name}}</td>
                            <td>{{$subject->lectures_count}}</td>
                            <td class="project-actions text-right">
                                <form action="{{url('admin/subjects/'.$subject->id)}}" method="post"
                                      onsubmit="return confirm('Do you really want to delete?');">
                                    @csrf
                                    @method('delete')
                                    <a class="btn btn-info btn-sm"
                                       href="{{url('admin/subjects/'.$subject->id.'/edit')}}">
                                        <i class="fas fa-pencil-alt" title="Edit"></i>
                                    </a>
                                    <button type="submit" class="btn btn-danger btn-sm">
                                        <i class="fas fa-trash" title="Delete"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('footer')
    <!-- DataTables -->
    <script src="{{asset('resources/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('resources/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('resources/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('resources/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
    <script>
        $(function () {
            $("#example").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        });
    </script>
@endsection