routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Auth\SessionController@login')->name('login');
Route::post('/login', 'Auth\SessionController@postLogin')->name('login');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'DashboardController@index');
    Route::get('logout', 'Auth\SessionController@logout');

    Route::get('change_password', 'Auth\PasswordManagerController@changePassword');
    Route::post('change_password', 'Auth\PasswordManagerController@postChangePassword');

    Route::get('lectures', 'LectureController@index');
    Route::get('lectures/download_class_note/{lecture_id}', 'LectureController@downloadClassNote');
    Route::get('lectures/download_lecture_sheet/{lecture_id}', 'LectureController@downloadLectureSheet');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::namespace('Admin')->group(function () {
        Route::prefix('admin')->group(function () {
            Route::resource('lectures', 'LectureController')->except(['show']);
            Route::resource('users', 'UserController')->except(['show']);
            Route::resource('batches', 'BatchController')->except(['show']);
            Route::resource('subjects', 'SubjectController')->except(['show']);
            Route::resource('configs', 'ConfigController')->except(['show']);

            Route::get('passwords/reset/{user_id}', 'PasswordManagerController@resetPassword');
            Route::post('passwords/reset/{user_id}', 'PasswordManagerController@postResetPassword');
        });
    });
});

app/Http/Controllers/Admin/BatchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Batch\CreateBatchValidation;
use App\Http\Requests\Admin\Batch\EditBatchValidation;
use App\Model\Batch;
use Illuminate\Http\Request;

class BatchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $batches = Batch::withCount('users')->get();

        return view('admin.batches.index', compact('batches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.batches.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateBatchValidation $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBatchValidation $request)
    {
        Batch::create(['name' => $request->get('name')]);

        return redirect('admin/batches')->with('successMessage', 'Batch created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $batch = Batch::find($id);

        return view('admin.batches.edit', compact('batch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  EditBatchValidation $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditBatchValidation $request, $id)
    {
        $batch = Batch::find($id);
        if ($batch) {
            $batch->update(['name' => $request->get('name')]);
        }

        return redirect('admin/batches')->with('successMessage', 'Batch updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $batch = Batch::find($id);
        if ($batch) {
            $batch->delete();
        }

        return redirect('admin/batches')->with('successMessage', 'Batch deleted successfully');
    }
}

resources/views/admin/batches/create.blade.php
@extends('layout.layout')
@section('title', 'Batch create')
@section('header')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active">Batch create</li>
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Batch create</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{url('admin/batches')}}" class="btn btn-primary float-right">
                        <i class="fas fa-arrow-left"></i> Back to list</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-body">
                        <form action="{{url('admin/batches')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name <span class="color-red">*</span></label>
                                <input type="text" id="name" name="name" value="{{old('name')}}"
                                       class="form-control <?php if ($errors->first('name') != null) echo 'is-invalid'; ?>">
                                <span class="error <?php if ($errors->first('name') != null) echo 'invalid-feedback'; ?>"
                                      style="display: inline;">{{$errors->first('name')}}</span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-success float-right">
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('footer')
@endsection

resources/views/admin/batches/edit.blade.php
@extends('layout.layout')
@section('title', 'Batch edit')
@section('header')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active">Batch edit</li>
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Batch edit</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{url('admin/batches')}}" class="btn btn-primary float-right">
                        <i class="fas fa-arrow-left"></i> Back to list</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-body">
                        <form action="{{url('admin/batches/'.$batch->id)}}" method="post">
                            @csrf
                            @method('put')
                            <div class="form-group">
                                <label for="name">Name <span class="color-red">*</span></label>
                                <input type="text" id="name" name="name"
                                       class="form-control <?php if ($errors->first('name') != null) echo 'is-invalid'; ?>"
                                       value="{{old('name',$batch->name)}}">
                                <span class="error <?php if ($errors->first('name') != null) echo 'invalid-feedback'; ?>"
                                      style="display: inline;">{{$errors->first('name')}}</span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Update" class="btn btn-success float-right">
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('footer')
@endsection

resources/views/admin/batches/index.blade.php
@extends('layout.layout')
@section('title', 'Batch list')
@section('header')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('resources/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
    <link rel="stylesheet"
          href="{{asset('resources/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active">Batch list</li>
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Batch list</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{url('admin/batches/create')}}" class="btn btn-primary float-right">
                        <i class="fas fa-plus"></i> Create new</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-body">
                @include('layout.flash_message')
                <table id="example" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th width="50%">Name</th>
                        <th>Number of users</th>
                        <th width="10%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($batches as $batch)
                        <tr>
                            <td>{{$batch->name}}</td>
                            <td>{{$batch->users_count}}</td>
                            <td class="project-actions text-right">
                                <form action="{{url('admin/batches/'.$batch->id)}}" method="post"
                                      onsubmit="return confirm('Do you really want to delete?');">
                                    @csrf
                                    @method('delete')
                                    <a class=" btn btn-info btn-sm
                                " href="{{url('admin/batches/'.$batch->id.'/edit')}}">
                                        <i class="fas fa-pencil-alt" title="Edit"></i>
                                    </a>
                                    <button type="submit" class="btn btn-danger btn-sm">
                                        <i class="fas fa-trash" title="Delete"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@stop
@section('footer')
    <!-- DataTables -->
    <script src="{{asset('resources/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('resources/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('resources/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('resources/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
    <script>
        $(function () {
            $("#example").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        });
    </script>
@endsection